# Description:
# AdaNet experimental code.
# **HIGHLY EXPERIMENTAL AND SUBJECT TO CHANGE**

licenses(["notice"])  # Apache 2.0

py_library(
    name = "experimental",
    srcs = ["__init__.py"],
    srcs_version = "PY3",
    visibility = ["//visibility:public"],
    deps = [
        "//adanet/experimental/controllers",
        "//adanet/experimental/keras",
        "//adanet/experimental/phases",
        "//adanet/experimental/schedulers",
        "//adanet/experimental/storages",
        "//adanet/experimental/work_units",
    ],
)
