# Description:
# AdaNet is a TensorFlow framework for adaptively learn neural networks as a
# dynamic ensemble of subnetworks.
# This is a reference implementation of AdaNet as a TensorFlow library.

package(default_visibility = [
    "//visibility:public",
])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "adanet",
    srcs = ["__init__.py"],
    visibility = [
    ],
    deps = [
        "//adanet/core",
    ],
)
