# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adanet/core/report.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='adanet/core/report.proto',
  package='adanet',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x61\x64\x61net/core/report.proto\x12\x06\x61\x64\x61net\"\x81\x01\n\x05Value\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x15\n\x0b\x66loat_value\x18\x02 \x01(\x02H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x05H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12\x15\n\x0b\x62ytes_value\x18\x05 \x01(\x0cH\x00\x42\x07\n\x05value\"\xb2\x03\n\x10SubnetworkReport\x12\x36\n\x07hparams\x18\x01 \x03(\x0b\x32%.adanet.SubnetworkReport.HparamsEntry\x12<\n\nattributes\x18\x02 \x03(\x0b\x32(.adanet.SubnetworkReport.AttributesEntry\x12\x36\n\x07metrics\x18\x03 \x03(\x0b\x32%.adanet.SubnetworkReport.MetricsEntry\x12\"\n\x1aincluded_in_final_ensemble\x18\x04 \x01(\x08\x12\x0c\n\x04name\x18\x05 \x01(\t\x1a=\n\x0cHparamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.adanet.Value:\x02\x38\x01\x1a@\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.adanet.Value:\x02\x38\x01\x1a=\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.adanet.Value:\x02\x38\x01\"a\n\x0fIterationReport\x12\x18\n\x10iteration_number\x18\x01 \x01(\x05\x12\x34\n\x12subnetwork_reports\x18\x02 \x03(\x0b\x32\x18.adanet.SubnetworkReportb\x06proto3')
)




_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='adanet.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_value', full_name='adanet.Value.string_value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='adanet.Value.float_value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='adanet.Value.int_value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='adanet.Value.bool_value', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_value', full_name='adanet.Value.bytes_value', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='adanet.Value.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=37,
  serialized_end=166,
)


_SUBNETWORKREPORT_HPARAMSENTRY = _descriptor.Descriptor(
  name='HparamsEntry',
  full_name='adanet.SubnetworkReport.HparamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='adanet.SubnetworkReport.HparamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='adanet.SubnetworkReport.HparamsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=474,
)

_SUBNETWORKREPORT_ATTRIBUTESENTRY = _descriptor.Descriptor(
  name='AttributesEntry',
  full_name='adanet.SubnetworkReport.AttributesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='adanet.SubnetworkReport.AttributesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='adanet.SubnetworkReport.AttributesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=540,
)

_SUBNETWORKREPORT_METRICSENTRY = _descriptor.Descriptor(
  name='MetricsEntry',
  full_name='adanet.SubnetworkReport.MetricsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='adanet.SubnetworkReport.MetricsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='adanet.SubnetworkReport.MetricsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=603,
)

_SUBNETWORKREPORT = _descriptor.Descriptor(
  name='SubnetworkReport',
  full_name='adanet.SubnetworkReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hparams', full_name='adanet.SubnetworkReport.hparams', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='adanet.SubnetworkReport.attributes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='adanet.SubnetworkReport.metrics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='included_in_final_ensemble', full_name='adanet.SubnetworkReport.included_in_final_ensemble', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='adanet.SubnetworkReport.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SUBNETWORKREPORT_HPARAMSENTRY, _SUBNETWORKREPORT_ATTRIBUTESENTRY, _SUBNETWORKREPORT_METRICSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=603,
)


_ITERATIONREPORT = _descriptor.Descriptor(
  name='IterationReport',
  full_name='adanet.IterationReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iteration_number', full_name='adanet.IterationReport.iteration_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subnetwork_reports', full_name='adanet.IterationReport.subnetwork_reports', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=702,
)

_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['string_value'])
_VALUE.fields_by_name['string_value'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['float_value'])
_VALUE.fields_by_name['float_value'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['int_value'])
_VALUE.fields_by_name['int_value'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['bool_value'])
_VALUE.fields_by_name['bool_value'].containing_oneof = _VALUE.oneofs_by_name['value']
_VALUE.oneofs_by_name['value'].fields.append(
  _VALUE.fields_by_name['bytes_value'])
_VALUE.fields_by_name['bytes_value'].containing_oneof = _VALUE.oneofs_by_name['value']
_SUBNETWORKREPORT_HPARAMSENTRY.fields_by_name['value'].message_type = _VALUE
_SUBNETWORKREPORT_HPARAMSENTRY.containing_type = _SUBNETWORKREPORT
_SUBNETWORKREPORT_ATTRIBUTESENTRY.fields_by_name['value'].message_type = _VALUE
_SUBNETWORKREPORT_ATTRIBUTESENTRY.containing_type = _SUBNETWORKREPORT
_SUBNETWORKREPORT_METRICSENTRY.fields_by_name['value'].message_type = _VALUE
_SUBNETWORKREPORT_METRICSENTRY.containing_type = _SUBNETWORKREPORT
_SUBNETWORKREPORT.fields_by_name['hparams'].message_type = _SUBNETWORKREPORT_HPARAMSENTRY
_SUBNETWORKREPORT.fields_by_name['attributes'].message_type = _SUBNETWORKREPORT_ATTRIBUTESENTRY
_SUBNETWORKREPORT.fields_by_name['metrics'].message_type = _SUBNETWORKREPORT_METRICSENTRY
_ITERATIONREPORT.fields_by_name['subnetwork_reports'].message_type = _SUBNETWORKREPORT
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['SubnetworkReport'] = _SUBNETWORKREPORT
DESCRIPTOR.message_types_by_name['IterationReport'] = _ITERATIONREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'adanet.core.report_pb2'
  # @@protoc_insertion_point(class_scope:adanet.Value)
  ))
_sym_db.RegisterMessage(Value)

SubnetworkReport = _reflection.GeneratedProtocolMessageType('SubnetworkReport', (_message.Message,), dict(

  HparamsEntry = _reflection.GeneratedProtocolMessageType('HparamsEntry', (_message.Message,), dict(
    DESCRIPTOR = _SUBNETWORKREPORT_HPARAMSENTRY,
    __module__ = 'adanet.core.report_pb2'
    # @@protoc_insertion_point(class_scope:adanet.SubnetworkReport.HparamsEntry)
    ))
  ,

  AttributesEntry = _reflection.GeneratedProtocolMessageType('AttributesEntry', (_message.Message,), dict(
    DESCRIPTOR = _SUBNETWORKREPORT_ATTRIBUTESENTRY,
    __module__ = 'adanet.core.report_pb2'
    # @@protoc_insertion_point(class_scope:adanet.SubnetworkReport.AttributesEntry)
    ))
  ,

  MetricsEntry = _reflection.GeneratedProtocolMessageType('MetricsEntry', (_message.Message,), dict(
    DESCRIPTOR = _SUBNETWORKREPORT_METRICSENTRY,
    __module__ = 'adanet.core.report_pb2'
    # @@protoc_insertion_point(class_scope:adanet.SubnetworkReport.MetricsEntry)
    ))
  ,
  DESCRIPTOR = _SUBNETWORKREPORT,
  __module__ = 'adanet.core.report_pb2'
  # @@protoc_insertion_point(class_scope:adanet.SubnetworkReport)
  ))
_sym_db.RegisterMessage(SubnetworkReport)
_sym_db.RegisterMessage(SubnetworkReport.HparamsEntry)
_sym_db.RegisterMessage(SubnetworkReport.AttributesEntry)
_sym_db.RegisterMessage(SubnetworkReport.MetricsEntry)

IterationReport = _reflection.GeneratedProtocolMessageType('IterationReport', (_message.Message,), dict(
  DESCRIPTOR = _ITERATIONREPORT,
  __module__ = 'adanet.core.report_pb2'
  # @@protoc_insertion_point(class_scope:adanet.IterationReport)
  ))
_sym_db.RegisterMessage(IterationReport)


_SUBNETWORKREPORT_HPARAMSENTRY._options = None
_SUBNETWORKREPORT_ATTRIBUTESENTRY._options = None
_SUBNETWORKREPORT_METRICSENTRY._options = None
# @@protoc_insertion_point(module_scope)
