# Description:
# AdaNet replay.

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "replay",
    srcs = ["__init__.py"],
    visibility = ["//adanet:__subpackages__"],
    deps = [
    ],
)
