# Description:
# AdaNet-TensorFlow compatibility logic.

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "tf_compat",
    srcs = ["__init__.py"],
    visibility = [
        "//adanet:__subpackages__",
    ],
    deps = [
    ],
)
