# Description:
# AdaNet ensemble logic.

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

py_library(
    name = "ensemble",
    srcs = ["__init__.py"],
    visibility = ["//adanet:__subpackages__"],
    deps = [
        ":ensembler",
    ],
)

py_library(
    name = "ensembler",
    srcs = ["ensembler.py"],
    deps = [
    ],
)
